spring:
  application:
    name: phone
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: ${PHONE_DB_URL}
    username: ${PHONE_DB_USERNAME}
    password: ${PHONE_DB_REDIS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${PHONE_REDIS_URL}
      port: 6379
      password: ${PHONE_DB_REDIS_PASSWORD}
  elasticsearch:
    uris: ${ES_URL}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
    ssl:
      truststore-location: classpath:ssl/es-truststore.jks
      truststore-password: ${ES_TRUSTSTORE_PASSWORD}
    connection-timeout: 5s
    socket-timeout: 30s

logging:
  level:
    org.springframework.security: DEBUG

gemini:
  api-key: ${GEMINI_API_KEY}

app:
  jwt:
    secret: ${PHONE_JWT_SECRET}
    expiration: 86400000
  vnpay:
    tmnCode: ${VNPAY_TMN_CODE}
    hashSecret: ${VNPAY_HASH_SECRET}
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:3000/payment/result    # e.g. https://yoursite.com/payment/result
    ipnUrl: ${VNPAY_IPN_URL}          # your webhook endpoint


